"""Reporting agent: incident report (markdown) with audit trail and explicit advisory disclaimer."""
import time

from agents.agent_state import AgentContext
from agents.tools.report_tools import save_report


class ReportingAgent:
    name = "reporting_agent"

    def run(self, ctx: AgentContext) -> dict:
        t0 = time.perf_counter()
        if "report_error" in ctx.faults:
            raise RuntimeError("injected report failure")
        i = ctx.incident
        ver, sev, dis, clr, sim = i.verification or {}, i.estimated_severity, i.dispatch or {}, i.clearance or {}, i.simulation or {}
        facts = {"severity": sev.level.value, "vehicles": i.vehicles_involved, "blocked_lanes": i.blocked_lanes,
                 "services": dis.get("services"), "delay_reduction_pct": (sim.get("improvement_pct") or {}).get("avg_delay_s")}
        summary_t = (f"An accident was detected on {i.location.road_segment} ({i.location.camera_id}) involving {i.vehicles_involved} vehicle(s), "
                     f"{i.blocked_lanes} lane(s) blocked, severity {sev.level.value}.")
        summary = ctx.llm.explain("reporting", facts, summary_t) if ctx.llm else summary_t
        L = [f"# Incident report {i.incident_id}", "",
             "> **Advisory document.** Generated by ATOS multi-agent system. All dispatch and traffic actions require human operator decisions; "
             "signal strategies were evaluated in simulation only.", "",
             "## Summary", summary, "",
             "## Key facts",
             f"| Field | Value |\n|---|---|\n| Status | {i.status.value} |\n| Camera / segment | {i.location.camera_id} / {i.location.road_segment} |\n"
             f"| Subtype | {i.subtype.value} |\n| Accident confidence | {ver.get('combined_score', 0):.0%} |\n"
             f"| Severity | {sev.level.value} ({sev.confidence:.0%}, uncertainty {sev.uncertainty.value}) |\n"
             f"| Vehicles involved | {i.vehicles_involved} ({', '.join(i.vehicle_types)}) |\n| Blocked lanes | {i.blocked_lanes} |\n"
             f"| Traffic density / avg speed / queue | {i.traffic_density_pct}% / {i.avg_speed_kmh} km/h / {i.queue_length_veh} veh |\n"
             f"| Approved by | {i.approved_by} at {i.approved_at} |\n", "",
             "## Verification (two-stage)"] + [f"- {r}" for r in ver.get("reasons", [])] + ["",
             "## Severity reasoning"] + [f"- {r}" for r in sev.reasons] + ["",
             "## Dispatch recommendation",
             f"Services: **{', '.join(dis.get('services', []))}**, priority **{dis.get('priority')}**, ETA (s): {dis.get('eta_s')}", "", dis.get("rationale", ""), "",
             "## Clearance plan",
             f"- Blocked edge: {clr.get('blocked_edge')}\n- Diversion (Route B): {' > '.join(clr.get('diversion_route', []))} (~{clr.get('diversion_eta_s')} s)\n"
             f"- Emergency corridor: {' > '.join(clr.get('emergency_route', []))} (~{clr.get('emergency_eta_s')} s)\n- Strategy: {clr.get('strategy')}", ""]
        for a in clr.get("signal_actions", []):
            L.append(f"  - {a['junction']}: {a['action']} ({a['seconds']:.0f}s)")
        if sim:
            b, t = sim["baseline"], sim["treatment"]
            L += ["", f"## Simulation ({sim['engine']}, {sim['seeds']} seeds): baseline vs system",
                  "| Metric | Baseline | With system | Improvement |\n|---|---|---|---|"]
            for k, lab in [("emergency_arrival_s", "Emergency arrival (s)"), ("queue_dissipation_s", "Queue dissipation (s)"),
                           ("avg_delay_s", "Avg delay per vehicle (s)"), ("recovery_s", "Congestion recovery (s)"), ("max_queue_veh", "Max queue (veh)")]:
                L.append(f"| {lab} | {b[k]:.0f} | {t[k]:.0f} | {sim['improvement_pct'].get(k, 0):.0f}% |")
        L += ["", "## Audit trail", "| Time | Actor | Transition | Note |\n|---|---|---|---|"]
        for e in ctx.store.events(i.incident_id):
            L.append(f"| {e['ts'][11:19]} | {e['actor']} | {e['from']} -> {e['to']} | {e['note']} |")
        if ctx.fallbacks_used:
            L += ["", f"_Fallback handlers used in this run: {', '.join(sorted(set(ctx.fallbacks_used)))}_"]
        text = "\n".join(L)
        ctx.log(self.name, "report", ["report_tools.save_report"], "report drafted", None, t0)
        return {"text": text}

    def commit(self, ctx: AgentContext, out: dict):
        ctx.incident.report_path = save_report(ctx.incident.incident_id, out["text"])
        ctx.store.save(ctx.incident)
